## Overview

there may not be a unique equilibrium for the cluster\
if the data does not contain a lot of signal\
that is, only a local minimum has been reached





## Hyperparameters

### n_clusters

how many clusters

### max_iter

how many iterations, default=300 is usually more than enough

### n_init

how many times will the alog be run, default=10. ensemble gives the final answer

In [1]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [2]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0])

In [3]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])